### ISSUE TITLE
Script to create Visio Services does not work.

### ISSUE THREAD

**Issue by csedwilliams** [PacktPublishing/Implementing-Microsoft-SharePoint-2019#1]
PS C:\Windows\system32> Add-pssnapin Microsoft.SharePoint.PowerShell 
New-SPVisioServiceApplication -Identity 'Visio Graphics Service Application' -ApplicationPool 'SharePoint Web Services Default' -CreateDefaultProxy
New-SPVisioServiceApplication : A parameter cannot be found that matches parameter name 'Identity'.
At line:2 char:31
+ New-SPVisioServiceApplication -Identity 'Visio Graphics Service Appli ...
+                               ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-SPVisioServiceApplication], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Office.Visio.Server.Cmdlet.NewSPVisioServiceApplication
 
It also didn't accept the command -CreateDefaultProxy

**Comment by packt-pradeeps** [comment]
Hi @csedwilliams ,

You are executing the commands in a fully incorrect manner. You have merged two commands as one that is why you are getting those errors. Try running the commands separately:

Command 1: `Add-pssnapin Microsoft.SharePoint.PowerShell`
Command 2: `New-SPVisioServiceApplication -Identity 'Visio Graphics Service Application' -ApplicationPool 'SharePoint Web Services Default' -CreateDefaultProxy`
